### ISSUE TITLE
calpatch scrolling issue with names

### ISSUE THREAD

**Issue by MACscr** [Zimbra-Community/zimbra-patches#3]
Right now with the current patch and on the daily view, when you scroll down on the schedule to look a couple hours into the day, you can no longer see the calendar names. Shouldnt they stay fixed at the top like the "All Day" even entries?

If we were going ideal setup, I would think the names would stay at the top, the all day entries below it, then the rest of the calendar that scrolls. Unfortunately I don't have an 8.6 system to see how it was handled before.

Thanks so much for your help on this, I sincerely appreciate it and I completely understand that you are doing this on a strictly volunteer basis.

**Comment by ghost** [comment]
Yeah, in 8.6 the calendar names would show always.

The problem here is that all the things you see on the screen are separate dom elements. So its not a single html table or anything like that. Rather separate html parts that are glued together with loads of not so nice code.

Moving the calendar names to the grid as they are now, allowed me to fix the scrolling... but that also means the names no longer stay on the screen.

Unfortunately I am unable to fix that... so you need an official patch for that. In the mean time the calendar day-view should be pretty doable with the patch until the real fix comes.

Or am I missing something?

**Comment by MACscr** [comment]
If they could be moved to the grid, why couldn’t they be moved to the same area as the all day events dom.
- Mark

**Comment by ghost** [comment]
okay, did not notice that, I moved the calendar titles to said place, and also restored the default `scrolling to 8AM function`.

So this should also be fixed.
